/**
 * Alias (español e inglés genérico) → `name_en` EXACTO del catálogo (dataset
 * free-exercise-db). Claves normalizadas: minúsculas, sin tildes. Cuando un
 * término es ambiguo ("press banca" casa con 10 filas) el alias fija la
 * variante canónica con barra, que es lo que el usuario suele hacer.
 */
export const EXERCISE_ALIASES: Record<string, string> = {
  // Pecho
  'press banca': 'Barbell Bench Press - Medium Grip',
  'press de banca': 'Barbell Bench Press - Medium Grip',
  'banca': 'Barbell Bench Press - Medium Grip',
  'bench press': 'Barbell Bench Press - Medium Grip',
  'bench': 'Barbell Bench Press - Medium Grip',
  'press banca mancuernas': 'Dumbbell Bench Press',
  'press banca con mancuernas': 'Dumbbell Bench Press',
  'press inclinado': 'Barbell Incline Bench Press - Medium Grip',
  'press inclinado barra': 'Barbell Incline Bench Press - Medium Grip',
  'press inclinado mancuernas': 'Incline Dumbbell Press',
  'press inclinado con mancuernas': 'Incline Dumbbell Press',
  'incline bench press': 'Barbell Incline Bench Press - Medium Grip',
  'press cerrado': 'Close-Grip Barbell Bench Press',
  'aperturas': 'Dumbbell Flyes',
  'aperturas con mancuernas': 'Dumbbell Flyes',
  'aperturas inclinadas': 'Incline Dumbbell Flyes',
  'cruce de poleas': 'Cable Crossover',
  'cruces de polea': 'Cable Crossover',
  'contractora': 'Butterfly',
  'pec deck': 'Butterfly',
  'flexiones': 'Pushups',
  'fondos': 'Dips - Triceps Version',
  'fondos en paralelas': 'Dips - Triceps Version',
  'fondos pecho': 'Dips - Chest Version',
  'dips': 'Dips - Triceps Version',
  // Hombro
  'press militar': 'Standing Military Press',
  'military press': 'Standing Military Press',
  'overhead press': 'Standing Military Press',
  'ohp': 'Standing Military Press',
  'press hombro': 'Dumbbell Shoulder Press',
  'press de hombro': 'Dumbbell Shoulder Press',
  'press hombro mancuernas': 'Dumbbell Shoulder Press',
  'press hombros': 'Dumbbell Shoulder Press',
  'shoulder press': 'Dumbbell Shoulder Press',
  'press arnold': 'Arnold Dumbbell Press',
  'elevaciones laterales': 'Side Lateral Raise',
  'laterales': 'Side Lateral Raise',
  'lateral raise': 'Side Lateral Raise',
  'pajaros': 'Cable Rear Delt Fly',
  'deltoide posterior': 'Cable Rear Delt Fly',
  'rear delt': 'Cable Rear Delt Fly',
  'reverse fly': 'Reverse Flyes',
  'face pull': 'Face Pull',
  'encogimientos': 'Barbell Shrug',
  'shrugs': 'Barbell Shrug',
  // Espalda
  'dominadas': 'Pullups',
  'pull ups': 'Pullups',
  'pull-ups': 'Pullups',
  'pullups': 'Pullups',
  'dominadas supinas': 'Chin-Up',
  'chin ups': 'Chin-Up',
  'jalon': 'Wide-Grip Lat Pulldown',
  'jalon al pecho': 'Wide-Grip Lat Pulldown',
  'jalon pecho': 'Wide-Grip Lat Pulldown',
  'lat pulldown': 'Wide-Grip Lat Pulldown',
  'remo': 'Bent Over Barbell Row',
  'remo con barra': 'Bent Over Barbell Row',
  'remo barra': 'Bent Over Barbell Row',
  'barbell row': 'Bent Over Barbell Row',
  'remo con mancuerna': 'One-Arm Dumbbell Row',
  'remo mancuerna': 'One-Arm Dumbbell Row',
  'remo a una mano': 'One-Arm Dumbbell Row',
  'dumbbell row': 'One-Arm Dumbbell Row',
  'remo en polea': 'Seated Cable Rows',
  'remo polea': 'Seated Cable Rows',
  'remo sentado': 'Seated Cable Rows',
  'cable row': 'Seated Cable Rows',
  'peso muerto': 'Barbell Deadlift',
  'deadlift': 'Barbell Deadlift',
  'peso muerto rumano': 'Romanian Deadlift',
  'rumano': 'Romanian Deadlift',
  'rdl': 'Romanian Deadlift',
  'peso muerto sumo': 'Sumo Deadlift',
  'hiperextensiones': 'Hyperextensions (Back Extensions)',
  'extensiones lumbares': 'Hyperextensions (Back Extensions)',
  'buenos dias': 'Good Morning',
  // Brazos
  'curl de biceps': 'Dumbbell Bicep Curl',
  'curl biceps': 'Dumbbell Bicep Curl',
  'curl con mancuernas': 'Dumbbell Bicep Curl',
  'curl mancuernas': 'Dumbbell Bicep Curl',
  'bicep curl': 'Dumbbell Bicep Curl',
  'curl con barra': 'Barbell Curl',
  'curl barra': 'Barbell Curl',
  'curl martillo': 'Hammer Curls',
  'hammer curl': 'Hammer Curls',
  'curl predicador': 'Preacher Curl',
  'curl scott': 'Preacher Curl',
  'press frances': 'EZ-Bar Skullcrusher',
  'rompecraneos': 'EZ-Bar Skullcrusher',
  'skullcrusher': 'EZ-Bar Skullcrusher',
  'extension de triceps': 'Triceps Pushdown',
  'extensiones de triceps': 'Triceps Pushdown',
  'triceps en polea': 'Triceps Pushdown',
  'triceps polea': 'Triceps Pushdown',
  'jalon de triceps': 'Triceps Pushdown',
  'tricep pushdown': 'Triceps Pushdown',
  'triceps con cuerda': 'Triceps Pushdown - Rope Attachment',
  // Pierna
  'sentadilla': 'Barbell Squat',
  'sentadillas': 'Barbell Squat',
  'sentadilla con barra': 'Barbell Squat',
  'squat': 'Barbell Squat',
  'back squat': 'Barbell Squat',
  'sentadilla frontal': 'Front Squat (Clean Grip)',
  'front squat': 'Front Squat (Clean Grip)',
  'sentadilla goblet': 'Goblet Squat',
  'goblet': 'Goblet Squat',
  'sentadilla bulgara': 'Split Squat with Dumbbells',
  'bulgaras': 'Split Squat with Dumbbells',
  'bulgarian split squat': 'Split Squat with Dumbbells',
  'zancadas': 'Dumbbell Lunges',
  'zancadas con mancuernas': 'Dumbbell Lunges',
  'lunges': 'Dumbbell Lunges',
  'zancadas con barra': 'Barbell Lunge',
  'prensa': 'Leg Press',
  'prensa de piernas': 'Leg Press',
  'leg press': 'Leg Press',
  'extension de cuadriceps': 'Leg Extensions',
  'extensiones de cuadriceps': 'Leg Extensions',
  'cuadriceps en maquina': 'Leg Extensions',
  'leg extension': 'Leg Extensions',
  'curl femoral': 'Lying Leg Curls',
  'femoral tumbado': 'Lying Leg Curls',
  'leg curl': 'Lying Leg Curls',
  'curl femoral sentado': 'Seated Leg Curl',
  'femoral sentado': 'Seated Leg Curl',
  'hip thrust': 'Barbell Hip Thrust',
  'empuje de cadera': 'Barbell Hip Thrust',
  'gemelos': 'Standing Calf Raises',
  'gemelos de pie': 'Standing Calf Raises',
  'elevacion de gemelos': 'Standing Calf Raises',
  'calf raise': 'Standing Calf Raises',
  'gemelos sentado': 'Seated Calf Raise',
  'paseo del granjero': "Farmer's Walk",
  'farmer walk': "Farmer's Walk",
  // Core
  'abdominales': 'Crunches',
  'crunch': 'Crunches',
  'plancha': 'Plank',
  'plank': 'Plank',
  'rueda abdominal': 'Ab Roller',
  'ab wheel': 'Ab Roller',
  'elevaciones de piernas': 'Hanging Leg Raise',
  'elevacion de piernas colgado': 'Hanging Leg Raise',
  'giros rusos': 'Russian Twist',
  // Cardio
  'cinta': 'Running, Treadmill',
  'correr': 'Running, Treadmill',
  'bici': 'Bicycling, Stationary',
  'bici estatica': 'Bicycling, Stationary',
  'eliptica': 'Elliptical Trainer',
  'remo maquina': 'Rowing, Stationary',
  'escaleras': 'Stairmaster',
};
